/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminSubscriptionsRouteImport } from './routes/_authenticated/_admin/admin.subscriptions'
import { Route as AuthenticatedAdminAdminModerationRouteImport } from './routes/_authenticated/_admin/admin.moderation'
import { Route as AuthenticatedAdminAdminGuideRouteImport } from './routes/_authenticated/_admin/admin.guide'
import { Route as AuthenticatedAdminAdminConfigRouteImport } from './routes/_authenticated/_admin/admin.config'
import { Route as AuthenticatedAdminAdminAdminsRouteImport } from './routes/_authenticated/_admin/admin.admins'
import { Route as AuthenticatedAdminAdminUsersIndexRouteImport } from './routes/_authenticated/_admin/admin.users.index'
import { Route as AuthenticatedAdminAdminUsersIdRouteImport } from './routes/_authenticated/_admin/admin.users.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminSubscriptionsRoute =
  AuthenticatedAdminAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminModerationRoute =
  AuthenticatedAdminAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminGuideRoute =
  AuthenticatedAdminAdminGuideRouteImport.update({
    id: '/guide',
    path: '/guide',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminConfigRoute =
  AuthenticatedAdminAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminAdminsRoute =
  AuthenticatedAdminAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminUsersIndexRoute =
  AuthenticatedAdminAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminUsersRoute,
  } as any)
const AuthenticatedAdminAdminUsersIdRoute =
  AuthenticatedAdminAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/admin/admins': typeof AuthenticatedAdminAdminAdminsRoute
  '/admin/config': typeof AuthenticatedAdminAdminConfigRoute
  '/admin/guide': typeof AuthenticatedAdminAdminGuideRoute
  '/admin/moderation': typeof AuthenticatedAdminAdminModerationRoute
  '/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRouteWithChildren
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminAdminUsersIdRoute
  '/admin/users/': typeof AuthenticatedAdminAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/admins': typeof AuthenticatedAdminAdminAdminsRoute
  '/admin/config': typeof AuthenticatedAdminAdminConfigRoute
  '/admin/guide': typeof AuthenticatedAdminAdminGuideRoute
  '/admin/moderation': typeof AuthenticatedAdminAdminModerationRoute
  '/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminAdminUsersIdRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/_authenticated/_admin/admin/admins': typeof AuthenticatedAdminAdminAdminsRoute
  '/_authenticated/_admin/admin/config': typeof AuthenticatedAdminAdminConfigRoute
  '/_authenticated/_admin/admin/guide': typeof AuthenticatedAdminAdminGuideRoute
  '/_authenticated/_admin/admin/moderation': typeof AuthenticatedAdminAdminModerationRoute
  '/_authenticated/_admin/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRouteWithChildren
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/users/$id': typeof AuthenticatedAdminAdminUsersIdRoute
  '/_authenticated/_admin/admin/users/': typeof AuthenticatedAdminAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin'
    | '/admin/admins'
    | '/admin/config'
    | '/admin/guide'
    | '/admin/moderation'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/admins'
    | '/admin/config'
    | '/admin/guide'
    | '/admin/moderation'
    | '/admin/subscriptions'
    | '/admin'
    | '/admin/users/$id'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/admin/login'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/admin/admins'
    | '/_authenticated/_admin/admin/config'
    | '/_authenticated/_admin/admin/guide'
    | '/_authenticated/_admin/admin/moderation'
    | '/_authenticated/_admin/admin/subscriptions'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/users/$id'
    | '/_authenticated/_admin/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/subscriptions': {
      id: '/_authenticated/_admin/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/moderation': {
      id: '/_authenticated/_admin/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/guide': {
      id: '/_authenticated/_admin/admin/guide'
      path: '/guide'
      fullPath: '/admin/guide'
      preLoaderRoute: typeof AuthenticatedAdminAdminGuideRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/config': {
      id: '/_authenticated/_admin/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/admins': {
      id: '/_authenticated/_admin/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/users/': {
      id: '/_authenticated/_admin/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminUsersRoute
    }
    '/_authenticated/_admin/admin/users/$id': {
      id: '/_authenticated/_admin/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminAdminUsersRouteChildren {
  AuthenticatedAdminAdminUsersIdRoute: typeof AuthenticatedAdminAdminUsersIdRoute
  AuthenticatedAdminAdminUsersIndexRoute: typeof AuthenticatedAdminAdminUsersIndexRoute
}

const AuthenticatedAdminAdminUsersRouteChildren: AuthenticatedAdminAdminUsersRouteChildren =
  {
    AuthenticatedAdminAdminUsersIdRoute: AuthenticatedAdminAdminUsersIdRoute,
    AuthenticatedAdminAdminUsersIndexRoute:
      AuthenticatedAdminAdminUsersIndexRoute,
  }

const AuthenticatedAdminAdminUsersRouteWithChildren =
  AuthenticatedAdminAdminUsersRoute._addFileChildren(
    AuthenticatedAdminAdminUsersRouteChildren,
  )

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminAdminsRoute: typeof AuthenticatedAdminAdminAdminsRoute
  AuthenticatedAdminAdminConfigRoute: typeof AuthenticatedAdminAdminConfigRoute
  AuthenticatedAdminAdminGuideRoute: typeof AuthenticatedAdminAdminGuideRoute
  AuthenticatedAdminAdminModerationRoute: typeof AuthenticatedAdminAdminModerationRoute
  AuthenticatedAdminAdminSubscriptionsRoute: typeof AuthenticatedAdminAdminSubscriptionsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRouteWithChildren
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminAdminsRoute: AuthenticatedAdminAdminAdminsRoute,
    AuthenticatedAdminAdminConfigRoute: AuthenticatedAdminAdminConfigRoute,
    AuthenticatedAdminAdminGuideRoute: AuthenticatedAdminAdminGuideRoute,
    AuthenticatedAdminAdminModerationRoute:
      AuthenticatedAdminAdminModerationRoute,
    AuthenticatedAdminAdminSubscriptionsRoute:
      AuthenticatedAdminAdminSubscriptionsRoute,
    AuthenticatedAdminAdminUsersRoute:
      AuthenticatedAdminAdminUsersRouteWithChildren,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
